// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateAccount(arg1:number,arg2:dto.CreateAccountInput):Promise<dto.AccountOutput>;

export function CreateCategory(arg1:number,arg2:dto.CreateCategoryInput):Promise<dto.CategoryOutput>;

export function DeleteAccount(arg1:number,arg2:number):Promise<void>;

export function DeleteCategory(arg1:number,arg2:number):Promise<void>;

export function DeleteTransaction(arg1:number,arg2:number):Promise<void>;

export function GetAccounts(arg1:number):Promise<Array<dto.AccountOutput>>;

export function GetCategories(arg1:number):Promise<Array<dto.CategoryOutput>>;

export function GetSummary(arg1:number):Promise<dto.FinanceSummary>;

export function GetTransactions(arg1:number,arg2:dto.TransactionFilter):Promise<Array<dto.TransactionOutput>>;

export function ImportTransactions(arg1:number,arg2:dto.ImportTransactionsInput):Promise<number>;

export function UpdateAccount(arg1:number,arg2:dto.UpdateAccountInput):Promise<dto.AccountOutput>;

export function UpdateCategory(arg1:number,arg2:dto.UpdateCategoryInput):Promise<dto.CategoryOutput>;

export function UpdateTransaction(arg1:number,arg2:number,arg3:any):Promise<void>;
