// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAccount(arg1, arg2) {
  return window['go']['services']['FinanceService']['CreateAccount'](arg1, arg2);
}

export function CreateCategory(arg1, arg2) {
  return window['go']['services']['FinanceService']['CreateCategory'](arg1, arg2);
}

export function DeleteAccount(arg1, arg2) {
  return window['go']['services']['FinanceService']['DeleteAccount'](arg1, arg2);
}

export function DeleteCategory(arg1, arg2) {
  return window['go']['services']['FinanceService']['DeleteCategory'](arg1, arg2);
}

export function DeleteTransaction(arg1, arg2) {
  return window['go']['services']['FinanceService']['DeleteTransaction'](arg1, arg2);
}

export function GetAccounts(arg1) {
  return window['go']['services']['FinanceService']['GetAccounts'](arg1);
}

export function GetCategories(arg1) {
  return window['go']['services']['FinanceService']['GetCategories'](arg1);
}

export function GetSummary(arg1) {
  return window['go']['services']['FinanceService']['GetSummary'](arg1);
}

export function GetTransactions(arg1, arg2) {
  return window['go']['services']['FinanceService']['GetTransactions'](arg1, arg2);
}

export function ImportTransactions(arg1, arg2) {
  return window['go']['services']['FinanceService']['ImportTransactions'](arg1, arg2);
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['services']['FinanceService']['UpdateAccount'](arg1, arg2);
}

export function UpdateCategory(arg1, arg2) {
  return window['go']['services']['FinanceService']['UpdateCategory'](arg1, arg2);
}

export function UpdateTransaction(arg1, arg2, arg3) {
  return window['go']['services']['FinanceService']['UpdateTransaction'](arg1, arg2, arg3);
}
