// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function ExportSettings(arg1:number):Promise<string>;

export function Get(arg1:number):Promise<dto.InvoiceEmailSettings>;

export function Update(arg1:number,arg2:dto.InvoiceEmailSettings):Promise<dto.InvoiceEmailSettings>;
