// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function Get(arg1:number):Promise<dto.UserSettings>;

export function Update(arg1:number,arg2:dto.UserSettings):Promise<dto.UserSettings>;
