// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';

export function CancelDownload():Promise<void>;

export function CheckForUpdate():Promise<void>;

export function GetUpdateState():Promise<update.State>;

export function InstallUpdate():Promise<void>;

export function SkipVersion():Promise<void>;

export function StartDownload():Promise<void>;
